@startuml "Reservierungssystem"

class Ticket{
- gültig: Bool
- saalnummer: string
- sitzplatz: string
- tarif: enum Tarif{Erwachsene, Kind, Ermäßigt}
+ validieren()
}

class Sitzplatz{
- reihe
- nummer
- kategorie

+ getInfo()
}

class Saal{
- saalnummer
- barrierefrei: Bool

{static}+ saalErstellen()
+ getSitzpleaetze()
+ löschen()
}

class Film{
- name: String
- fskKennzeichnung: String
- omdbId: String

{static} + FilmAngebot():Film[]
{static}+ filmErstellen()
+ getInfo()
+ löschen()
+ getOmdbId()
}

class Vorstellung{
    - datum: String
    - uhrzeit: String
    - freieSitze: Sitzplatz[*]

    {static}+ vorstellungErstellen()
    + getInfo()
    + bucheSitzplatz(Sitzplatz)
    + getFreieSitze(): Sitzplatz[*]
    + preisFestlegen()
}

class Buchung{
    - buchungsID
    - status: enum Status{offen, storniert, bezahlt}
    - zahlungsmethode: enum Zahlungsmethode{Kreditkarte, Paypal, Lastschrift}

    + statusAendern()
    + bezahlen()
}

class Account{
    - name: String
    - email: String
    - rolle: enum Rolle{Admin, Mitarbeiter, User}

    {static}+ accountErstellen()
}

Saal "1"*--"*" Sitzplatz: enthält Sitze

Vorstellung "0..*" -- "1" Saal: hat
Vorstellung "0..*" -- "1" Film: zeigt

Buchung "0..*"--"1" Account
Buchung "0..*"-"1" Vorstellung
Buchung "1" *- "1..*" Ticket

@enduml